return {
PlaceObj('ModItemCode', {
	'name', "VIPTracker",
	'FileName', "Code/VIPTracker.lua",
}),
PlaceObj('ModItemXTemplate', {
	__copy_group = "CCC",
	comment = "VIPDeadOverview",
	group = "CCC",
	id = "VIPDeadOverview",
	PlaceObj('XTemplateTemplate', {
		'__context', function (parent, context) return context or {} end,
		'__template', "NewOverlayDlg",
		'MinWidth', 500,
		'InitialMode', "deadVIPs",
		'InternalModes', "deadVIPs",
	}, {
		PlaceObj('XTemplateTemplate', {
			'__template', "CommandCenterTitle",
			'Title', T{987234920023, --[[ModItemXTemplate VIPDeadOverview Title]] "DEPARTED VIPS"},
		}),
		PlaceObj('XTemplateWindow', {
			'__class', "XContentTemplate",
			'Id', "idContent",
			'IdNode', false,
		}, {
			PlaceObj('XTemplateWindow', {
				'__class', "XSizeConstrainedWindow",
			}, {
				PlaceObj('XTemplateWindow', {
					'Margins', box(115, 0, 0, 15),
					'Padding', box(63, 0, 0, 0),
					'Dock', "top",
					'LayoutMethod', "HList",
				}, {
					PlaceObj('XTemplateWindow', {
						'comment', "name",
						'__class', "XText",
						'Id', "VIPName",
						'Padding', box(0, 0, 0, 0),
						'MinWidth', 255,
						'MaxWidth', 255,
						'Clip', false,
						'HandleMouse', false,
						'TextStyle', "OverviewItemSection",
						'Translate', true,
						'Text', T{854866001515, --[[ModItemXTemplate VIPDeadOverview Text]] "Name"},
						'WordWrap', false,
						'TextHAlign', "left",
						'TextVAlign', "center",
					}),
					PlaceObj('XTemplateWindow', {
						'comment', "Died Sol",
						'__class', "XText",
						'Id', "diedSol",
						'Padding', box(0, 0, 0, 0),
						'MinWidth', 90,
						'MaxWidth', 90,
						'Clip', false,
						'HandleMouse', false,
						'TextStyle', "OverviewItemSection",
						'Translate', true,
						'Text', T{987234920024, --[[ModItemXTemplate VIPDeadOverview Text]] "Died/Left"},
						'WordWrap', false,
						'TextHAlign', "center",
						'TextVAlign', "center",
					}),
					PlaceObj('XTemplateWindow', {
						'comment', "Age",
						'__class', "XText",
						'Id', "ageAtDeath",
						'Padding', box(0, 0, 0, 0),
						'MinWidth', 90,
						'MaxWidth', 90,
						'Clip', false,
						'HandleMouse', false,
						'TextStyle', "OverviewItemSection",
						'Translate', true,
						'Text', T{987234920025, --[[ModItemXTemplate VIPDeadOverview Text]] "Age"},
						'WordWrap', false,
						'TextHAlign', "center",
						'TextVAlign', "center",
					}),
					PlaceObj('XTemplateWindow', {
						'comment', "reason",
						'__class', "XText",
						'Id', "deathReason",
						'Padding', box(0, 0, 0, 0),
						'MinWidth', 600,
						'MaxWidth', 600,
						'Clip', false,
						'HandleMouse', false,
						'TextStyle', "OverviewItemSection",
						'Translate', true,
						'Text', T{987234920026, --[[ModItemXTemplate VIPDeadOverview Text]] "Cause"},
						'WordWrap', false,
						'TextHAlign', "left",
						'TextVAlign', "center",
					}),
					}),
				PlaceObj('XTemplateWindow', {
					'__class', "XList",
					'Id', "idList",
					'BorderWidth', 0,
					'Padding', box(0, 0, 0, 0),
					'MinWidth', 1079,
					'MaxWidth', 1079,
					'UniformRowHeight', true,
					'Clip', false,
					'Background', RGBA(0, 0, 0, 0),
					'FocusedBackground', RGBA(0, 0, 0, 0),
					'VScroll', "idScroll",
					'ShowPartialItems', false,
				}, {
					PlaceObj('XTemplateForEach', {
						'comment', "deadVIPs",
						'array', function (parent, context)
							local DepartedList = VIPTracker.DepartedList
							parent:ResolveId("idTitle"):SetTitle(T{987234920027, "<white><count></white> DEPARTED VIPS", count = #DepartedList})
							return DepartedList
						end,
						'__context', function (parent, context, item, i, n) return item end,
						'run_before', function (parent, context, item, i, n)
							NewXVirtualContent(parent, context, "VIPDeadOverviewRow", 1079, 46)
						end,
					}),
					}),
				PlaceObj('XTemplateWindow', {
					'__class', "XText",
					'Id', "idNoResults",
					'Dock', "box",
					'HAlign', "center",
					'VAlign', "center",
					'Visible', false,
					'HandleMouse', false,
					'TextStyle', "InGameTitle",
					'Translate', true,
					'Text', T{539668092498, --[[ModItemXTemplate VIPDeadOverview Text]] "Empty list"},
				}),
				PlaceObj('XTemplateCode', {
					'run', function (self, parent, context)
						local list = parent:ResolveId("idList")
						parent:ResolveId("idNoResults"):SetVisible(#list == 0)
					end,
				}),
				PlaceObj('XTemplateTemplate', {
					'__template', "ScrollbarNew",
					'Id', "idScroll",
					'Margins', box(99, 0, 0, 0),
					'Target', "idList",
				}),
				}),
			}),
		PlaceObj('XTemplateAction', {
			'ActionId', "back",
			'ActionName', T{216830668315, --[[ModItemXTemplate VIPDeadOverview ActionName]] "BACK"},
			'ActionToolbar', "ActionBar",
			'ActionShortcut', "Escape",
			'ActionGamepad', "ButtonB",
			'OnActionEffect', "back",
		}),
		}),
}),
PlaceObj('ModItemXTemplate', {
	__is_kind_of = "XContextControl",
	comment = "VIPDeadOverviewRow",
	id = "VIPDeadOverviewRow",
	group = "CCC",
	PlaceObj('XTemplateTemplate', {
		'__template', "CommandCenterRow",
		'RolloverText', T{602527858023, --[[ModItemXTemplate  RolloverText]] "<OverviewInfo>"},
		'RolloverHint', T{221573023887, --[[ModItemXTemplate  RolloverHint]] "<image UI/Infopanel/left_click.tga 1400><image UI/Infopanel/left_click.tga 1400> Select"},
		'RolloverHintGamepad', T{986296804256, --[[ModItemXTemplate  RolloverHintGamepad]] "<image UI/PS4/Cross.tga> Select"},
		'OnContextUpdate', function (self, context, ...)
			UpdateUICommandCenterRow(self, context, "deadVIP")
			XContextControl.OnContextUpdate(self, context, ...)
		end,
	}, {
		PlaceObj('XTemplateWindow', {
			'__class', "XText",
			'Margins', box(10, 0, 0, 0),
			'Padding', box(0, 0, 0, 0),
			'HAlign', "left",
			'VAlign', "center",
			'MinWidth', 255,
			'MaxWidth', 255,
			'TextStyle', "OverviewItemName",
			'Translate', true,
			'Text', T{447555686252, --[[ModItemXTemplate  Text]] "<DisplayName>"},
			'Shorten', true,
		}),
		PlaceObj('XTemplateWindow', {
			'__class', "XText",
			'Id', "diedSol",
			'Padding', box(0, 0, 0, 0),
			'HAlign', "center",
			'VAlign', "center",
			'MinWidth', 90,
			'MaxWidth', 90,
			'TextStyle', "OverviewItemValue",
			'WordWrap', false,
			'TextHAlign', "center",
			'TextVAlign', "center",
		}),
		PlaceObj('XTemplateWindow', {
			'__class', "XText",
			'Id', "ageAtDeath",
			'Padding', box(0, 0, 0, 0),
			'HAlign', "center",
			'VAlign', "center",
			'MinWidth', 90,
			'MaxWidth', 90,
			'TextStyle', "OverviewItemValue",
			'WordWrap', false,
			'TextHAlign', "center",
			'TextVAlign', "center",
		}),
		PlaceObj('XTemplateWindow', {
			'__class', "XText",
			'Id', "deathReason",
			'Padding', box(0, 0, 0, 0),
			'HAlign', "left",
			'VAlign', "center",
			'MinWidth', 600,
			'MaxWidth', 600,
			'TextStyle', "OverviewItemValue",
			'WordWrap', false,
			'TextHAlign', "left",
			'TextVAlign', "center",
		}),
		}),
}),
PlaceObj('ModItemXTemplate', {
	__copy_group = "CCC",
	comment = "VIPActivityOverview",
	group = "CCC",
	id = "VIPActivityOverview",
	PlaceObj('XTemplateTemplate', {
		'__context', function (parent, context) return context or {} end,
		'__template', "NewOverlayDlg",
		'MinWidth', 500,
		'InitialMode', "VIPActivityLog",
		'InternalModes', "VIPActivityLog",
	}, {
		PlaceObj('XTemplateTemplate', {
			'__template', "CommandCenterTitle",
			'Title', T{987234920054, "VIP ACTIVITY LOG"},
		}),
		PlaceObj('XTemplateWindow', {
			'__class', "XContentTemplate",
			'Id', "idContent",
			'IdNode', false,
		}, {
			PlaceObj('XTemplateWindow', {
				'__class', "XSizeConstrainedWindow",
			}, {
				PlaceObj('XTemplateWindow', {
					'Margins', box(115, 0, 0, 15),
					'Padding', box(63, 0, 0, 0),
					'Dock', "top",
					'LayoutMethod', "HList",
				}, {
					PlaceObj('XTemplateWindow', {
						'comment', "name",
						'__class', "XText",
						'Id', "name",
						'Padding', box(0, 0, 0, 0),
						'MinWidth', 255,
						'MaxWidth', 255,
						'Clip', false,
						'HandleMouse', false,
						'TextStyle', "OverviewItemSection",
						'Translate', true,
						'Text', T{854866001515, --[[ModItemXTemplate VIPActivityOverview Text]] "Name"},
						'WordWrap', false,
						'TextHAlign', "left",
						'TextVAlign', "center",
					}),
					PlaceObj('XTemplateWindow', {
						'comment', "Sol",
						'__class', "XText",
						'Id', "sol",
						'Padding', box(0, 0, 0, 0),
						'MinWidth', 90,
						'MaxWidth', 90,
						'Clip', false,
						'HandleMouse', false,
						'TextStyle', "OverviewItemSection",
						'Translate', true,
						'Text', T{987234920055, --[[ModItemXTemplate VIPActivityOverview Text]] "Sol"},
						'WordWrap', false,
						'TextHAlign', "center",
						'TextVAlign', "center",
					}),
					PlaceObj('XTemplateWindow', {
						'comment', "activity log message",
						'__class', "XText",
						'Id', "log_msg",
						'Padding', box(0, 0, 0, 0),
						'MinWidth', 700,
						'MaxWidth', 700,
						'Clip', false,
						'HandleMouse', false,
						'TextStyle', "OverviewItemSection",
						'Translate', true,
						'Text', T{987234920056, --[[ModItemXTemplate VIPDeadOverview Text]] "Activity"},
						'WordWrap', false,
						'TextHAlign', "left",
						'TextVAlign', "center",
					}),
					}),
				PlaceObj('XTemplateWindow', {
					'__class', "XList",
					'Id', "idList",
					'BorderWidth', 0,
					'Padding', box(0, 0, 0, 0),
					'MinWidth', 1079,
					'MaxWidth', 1079,
					'UniformRowHeight', true,
					'Clip', false,
					'Background', RGBA(0, 0, 0, 0),
					'FocusedBackground', RGBA(0, 0, 0, 0),
					'VScroll', "idScroll",
					'ShowPartialItems', false,
				}, {
					PlaceObj('XTemplateForEach', {
						'comment', "VIPActivityLogs",
						'array', function (parent, context)
							return VIPTracker.ActivityLog
						end,
						'__context', function (parent, context, item, i, n) return item end,
						'run_before', function (parent, context, item, i, n)
							NewXVirtualContent(parent, context, "VIPActivityOverviewRow", 1079, 46)
						end,
					}),
					}),
				PlaceObj('XTemplateWindow', {
					'__class', "XText",
					'Id', "idNoResults",
					'Dock', "box",
					'HAlign', "center",
					'VAlign', "center",
					'Visible', false,
					'HandleMouse', false,
					'TextStyle', "InGameTitle",
					'Translate', true,
					'Text', T{539668092498, --[[ModItemXTemplate VIPActivityOverview Text]] "Empty list"},
				}),
				PlaceObj('XTemplateCode', {
					'run', function (self, parent, context)
						local list = parent:ResolveId("idList")
						parent:ResolveId("idNoResults"):SetVisible(#list == 0)
					end,
				}),
				PlaceObj('XTemplateTemplate', {
					'__template', "ScrollbarNew",
					'Id', "idScroll",
					'Margins', box(99, 0, 0, 0),
					'Target', "idList",
				}),
				}),
			}),
		PlaceObj('XTemplateAction', {
			'ActionId', "back",
			'ActionName', T{216830668315, --[[ModItemXTemplate VIPActivityOverview ActionName]] "BACK"},
			'ActionToolbar', "ActionBar",
			'ActionShortcut', "Escape",
			'ActionGamepad', "ButtonB",
			'OnActionEffect', "back",
		}),
		}),
}),
PlaceObj('ModItemXTemplate', {
	__is_kind_of = "XContextControl",
	comment = "VIPActivityOverviewRow",
	id = "VIPActivityOverviewRow",
	group = "CCC",
	PlaceObj('XTemplateTemplate', {
		'__template', "CommandCenterRow",
		'OnContextUpdate', function (self, context, ...)
			UpdateUICommandCenterRow(self, context, "VIPActivityLog")
			XContextControl.OnContextUpdate(self, context, ...)
		end,
	}, {
		PlaceObj('XTemplateWindow', {
			'__class', "XText",
			'Id', "name",
			'Margins', box(10, 0, 0, 0),
			'Padding', box(0, 0, 0, 0),
			'HAlign', "left",
			'VAlign', "center",
			'MinWidth', 255,
			'MaxWidth', 255,
			'TextStyle', "OverviewItemName",
			'Translate', true,
			'Shorten', true,
		}),
		PlaceObj('XTemplateWindow', {
			'__class', "XText",
			'Id', "sol",
			'Padding', box(0, 0, 0, 0),
			'HAlign', "center",
			'VAlign', "center",
			'MinWidth', 90,
			'MaxWidth', 90,
			'TextStyle', "OverviewItemValue",
			'WordWrap', false,
			'TextHAlign', "center",
			'TextVAlign', "center",
		}),
		PlaceObj('XTemplateWindow', {
			'__class', "XText",
			'Id', "log_msg",
			'Padding', box(0, 0, 0, 0),
			'HAlign', "left",
			'VAlign', "center",
			'MinWidth', 700,
			'MaxWidth', 700,
			'TextStyle', "OverviewItemValue",
			'WordWrap', false,
			'TextHAlign', "left",
			'TextVAlign', "center",
		}),
		}),
}),
}
