return PlaceObj('ModDef', {
	'title', "VIP Tracker",
	'id', "Dawnmist_VIPTracker",
	'steam_id', "1574069378",
	'image', "Preview.png",
	'last_changes', "Improve compatibility with other mods that add new death reasons",
	'author', "Dawnmist",
	'version', 7,
	'lua_revision', 237920,
	'code', {"Code/VIPTracker.lua"},
	'saved', 1543110572,
	'TagInterface', true,
	'TagTools', true,
	'TagOther', true,
})